name: Build macOS App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install moviepy
        pip install imageio_ffmpeg
        pip install telethon
        pip install flask
        pip install python-dotenv
        pip install pillow
        pip install send2trash
        pip install pyperclip
        pip install cryptg
    
    - name: Build executable
      run: |
        chmod +x ffmpeg
        pyinstaller --onefile \
                   --noconfirm \
                   --add-binary "ffmpeg:." \
                   --hidden-import=imageio_ffmpeg \
                   --collect-all imageio_ffmpeg \
                   --console "crop.py"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: macOS-app
        path: dist/
